# Generated by Django 5.0.2 on 2024-02-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_name_ner_ner_rename_name_step_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step',
            field=models.TextField(max_length=2000),
        ),
    ]
