# Generated by Django 5.1.1 on 2024-10-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_is_public'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustomization',
            name='saved_dishes',
            field=models.ManyToManyField(blank=True, to='recipes.recipe'),
        ),
    ]
